id     = "IDL"
name   = "Idl"
header = "options/idl_options.h"

[[option]]
  name       = "idlRewriteEq"
  category   = "regular"
  long       = "idl-rewrite-equalities"
  type       = "bool"
  default    = "false"
  help       = "enable rewriting equalities into two inequalities in IDL solver (default is disabled)"
